---
name: build-and-publish-dockerhub
on:
  push:
    branches:
      - main
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build image
        shell: bash
        run: |
          docker build -t ${{ vars.DOCKERHUB_TAG }} .
      - name: login to dockerhub
        shell: bash
        run: |
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
      - name: publish to dockerhub
        shell: bash
        run: |
          docker push ${{ vars.DOCKERHUB_TAG }}

